"use client"
import Navbar from '@/components/Navbar'
import './globals.css'
import "react-toastify/dist/ReactToastify.css";
import { ThemeProvider } from 'next-themes'
import Footer from '@/components/Footer'
import Head from './head'


// export const meta = {
//   title: "Filip's portfolio ",
//   description: 'Generated by Filip Ušković',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <Head/>
        <body suppressHydrationWarning={true}>
          <ThemeProvider enableSystem={true} attribute='class'>
       <Navbar />

       {children}
      </ThemeProvider>
      <Footer />
      </body>
      
    </html>
  )
}
